apiVersion: apps/v1
kind: Deployment
metadata:
    name: subscriber
    labels:
        app: subscriber
spec:
    replicas: 3
    selector:
        matchLabels:
            app: subscriber
    template:
        metadata:
            labels:
                app: subscriber
        spec:
            containers:
                - name: subscriber
                  ports:
                      - containerPort: 8080
                  readinessProbe:
                      httpGet:
                          path: /ready
                          port: 8080
                      initialDelaySeconds: 3
                      periodSeconds: 3
                  livenessProbe:
                      httpGet:
                          path: /live
                          port: 8080
                      initialDelaySeconds: 3
                      periodSeconds: 3
