apiVersion: v1
kind: Service
metadata:
  name: socket-server
  namespace: dev
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: socket-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: socket-server
  name: socket-server
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socket-server
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      containers:
      - env:
        - name: PORT
          value: 3000
        - name: LOG_LEVEL
          value: log,error,warn.debug
        image: socket-server
        name: socket-server
        ports:
        - containerPort: 80
