apiVersion: apps/v1
kind: Deployment
metadata:
    name: socket-server
spec:
    template:
        spec:
            containers:
                - name: socket-server
                  image: $DOCKER_IMAGE
