apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: ingress-socket-server
spec:
    rules:
        - host: socket-server.127.0.0.1.nip.io
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: socket-server
                        servicePort: 80
