apiVersion: apps/v1
kind: Deployment
metadata:
    name: subscriber
spec:
    replicas: 1
    template:
        spec:
            containers:
                - name: subscriber
                  image: $DOCKER_IMAGE
